# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("avatar", models.URLField(blank=True, null=True)),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(default="de", max_length=10)),
                ("timezone", models.CharField(default="Europe/Berlin", max_length=50)),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_enabled", models.BooleanField(default=False)),
                ("rollout_percentage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feature_flags",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "permissions",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name der Organisation", max_length=255, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-freundlicher Identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Hauptkontakt-Email", max_length=254, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL zum Firmenlogo",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Primary brand color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1E40AF",
                        help_text="Secondary brand color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Steuernummer / VAT",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Handelsregisternummer",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Firmen-Website",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(default="Deutschland", max_length=100)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("max_users", models.IntegerField(default=5)),
                ("max_properties", models.IntegerField(default=10)),
                ("storage_limit_gb", models.IntegerField(default=5)),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        help_text="Default currency (ISO code)",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Berlin",
                        help_text="Default timezone",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="de", help_text="Default language code", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription_start_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("employee", "Employee"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("avatar", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="accounts.role"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("agent", "Agent"),
                            ("viewer", "Viewer"),
                        ],
                        default="agent",
                        max_length=20,
                    ),
                ),
                ("can_manage_properties", models.BooleanField(default=True)),
                ("can_manage_documents", models.BooleanField(default=True)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("can_export_data", models.BooleanField(default=False)),
                (
                    "scopes",
                    models.JSONField(
                        blank=True, default=list, help_text="List of permission scopes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenant_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["email"], name="tenants_email_64287b_idx"),
        ),
        migrations.AddField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles", to="accounts.permission"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="accounts.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["category"], name="permissions_categor_b3ddb9_idx"
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="accounts.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["tenant", "role"], name="user_profil_tenant__9423f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["tenant", "is_active"], name="user_profil_tenant__7e264a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(
                fields=["user", "tenant"], name="tenant_user_user_id_6c8fb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(
                fields=["tenant", "role"], name="tenant_user_tenant__24f612_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantuser",
            unique_together={("user", "tenant")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["tenant", "is_system"], name="roles_tenant__b7923f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["tenant", "is_enabled"], name="feature_fla_tenant__6d3c3a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featureflag",
            unique_together={("tenant", "name")},
        ),
    ]
