# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("property", "Property"),
                            ("contact", "Contact"),
                            ("task", "Task"),
                            ("appointment", "Appointment"),
                            ("document", "Document"),
                            ("financial", "Financial"),
                            ("message", "Message"),
                            ("team", "Team"),
                            ("cim", "CIM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                (
                    "min_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="low",
                        help_text="Minimale Priorität für diese Kategorie",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
                "indexes": [
                    models.Index(
                        fields=["tenant", "user"], name="notificatio_tenant__52fe84_idx"
                    )
                ],
                "unique_together": {("tenant", "user", "category")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("reminder", "Reminder"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("property", "Property"),
                            ("contact", "Contact"),
                            ("task", "Task"),
                            ("appointment", "Appointment"),
                            ("document", "Document"),
                            ("financial", "Financial"),
                            ("message", "Message"),
                            ("team", "Team"),
                            ("cim", "CIM"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL zum Navigieren bei Klick",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        help_text="Label für Action-Button",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "related_entity_type",
                    models.CharField(
                        blank=True,
                        help_text="z.B. 'property', 'contact', 'task'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "related_entity_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "related_entity_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zusätzliche Daten (Icons, Farben, etc.)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Automatisches Löschen nach diesem Datum",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Empfänger der Benachrichtigung",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "user", "read", "created_at"],
                        name="notificatio_tenant__63a416_idx",
                    ),
                    models.Index(
                        fields=["tenant", "user", "category"],
                        name="notificatio_tenant__85ecb3_idx",
                    ),
                    models.Index(
                        fields=["tenant", "user", "priority"],
                        name="notificatio_tenant__4a0788_idx",
                    ),
                    models.Index(
                        fields=["tenant", "type"], name="notificatio_tenant__76973e_idx"
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="notificatio_tenant__f87df4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="notificatio_expires_66996e_idx"
                    ),
                ],
            },
        ),
    ]
