# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="Lead", max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar", models.URLField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hauptbudget / Potenzialwert",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("budget_currency", models.CharField(default="EUR", max_length=3)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("lead_score", models.IntegerField(default=0)),
                (
                    "lead_score_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed lead score breakdown and signals",
                    ),
                ),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional contact information like birth_date, source, etc.",
                    ),
                ),
                (
                    "address",
                    models.JSONField(
                        blank=True, default=dict, help_text="Contact address details"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about contact", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contacts",
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="contacts_tenant__5850a0_idx"
                    ),
                    models.Index(
                        fields=["tenant", "lead_score"],
                        name="contacts_tenant__3bcf0b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="contacts_tenant__1beb0e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "priority"],
                        name="contacts_tenant__2435c1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "category"],
                        name="contacts_tenant__892561_idx",
                    ),
                ],
            },
        ),
    ]
