# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("akquise", "Akquise"),
                            ("vorbereitung", "Vorbereitung"),
                            ("aktiv", "Aktiv"),
                            ("reserviert", "Reserviert"),
                            ("verkauft", "Verkauft"),
                            ("zurückgezogen", "Zurückgezogen"),
                        ],
                        default="vorbereitung",
                        max_length=50,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                            ("office", "Office"),
                            ("retail", "Retail"),
                            ("industrial", "Industrial"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_currency", models.CharField(default="EUR", max_length=3)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("rent", "Rent")],
                        default="sale",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "living_area",
                    models.IntegerField(
                        blank=True, help_text="Wohnfläche in m²", null=True
                    ),
                ),
                (
                    "total_area",
                    models.IntegerField(
                        blank=True, help_text="Gesamtfläche in m²", null=True
                    ),
                ),
                (
                    "plot_area",
                    models.IntegerField(
                        blank=True, help_text="Grundstücksfläche in m²", null=True
                    ),
                ),
                (
                    "rooms",
                    models.IntegerField(
                        blank=True, help_text="Anzahl Zimmer", null=True
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True, help_text="Anzahl Schlafzimmer", null=True
                    ),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        blank=True, help_text="Anzahl Bäder", null=True
                    ),
                ),
                (
                    "floors",
                    models.IntegerField(
                        blank=True, help_text="Anzahl Etagen", null=True
                    ),
                ),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "energy_class",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "energy_consumption",
                    models.IntegerField(blank=True, help_text="kWh/m²a", null=True),
                ),
                (
                    "heating_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "energy_certificate_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bedarfsausweis", "Bedarfsausweis"),
                            ("verbrauchsausweis", "Verbrauchsausweis"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "energy_certificate_valid_until",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "energy_certificate_issue_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "co2_emissions",
                    models.IntegerField(
                        blank=True, help_text="CO₂-Emissionen in kg/m²a", null=True
                    ),
                ),
                (
                    "coordinates_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "coordinates_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste von Ausstattungsmerkmalen",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags für Kategorisierung"
                    ),
                ),
                (
                    "auto_publish_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Automatisch auf Portalen aktualisieren",
                    ),
                ),
                (
                    "auto_publish_portals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste von Portalen für Auto-Publish",
                    ),
                ),
                (
                    "auto_publish_interval_hours",
                    models.IntegerField(
                        default=2,
                        help_text="Intervall in Stunden für Auto-Publish (2.4h = 10x täglich)",
                    ),
                ),
                (
                    "last_auto_published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Letzter Auto-Publish Zeitpunkt",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyFeatures",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "energy_class",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "heating_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("parking_spaces", models.IntegerField(blank=True, null=True)),
                ("balcony", models.BooleanField(default=False)),
                ("garden", models.BooleanField(default=False)),
                ("elevator", models.BooleanField(default=False)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_features",
            },
        ),
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("google_maps_api_key", models.TextField(blank=True, null=True)),
                ("immoscout_client_id", models.TextField(blank=True, null=True)),
                ("immoscout_client_secret", models.TextField(blank=True, null=True)),
                ("immoscout_access_token", models.TextField(blank=True, null=True)),
                ("immoscout_refresh_token", models.TextField(blank=True, null=True)),
                (
                    "immoscout_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("immowelt_api_key", models.TextField(blank=True, null=True)),
                ("ebay_api_key", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_settings",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "integration_settings",
            },
        ),
        migrations.CreateModel(
            name="ExposeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("kauf", "Kauf"),
                            ("miete", "Miete"),
                            ("investor", "Investor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("neutral", "Neutral"),
                            ("elegant", "Elegant"),
                            ("kurz", "Kurz"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")], max_length=10
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("short", "Kurz"),
                            ("standard", "Standard"),
                            ("long", "Lang"),
                        ],
                        max_length=20,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expose_versions",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "expose_versions",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=100)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "contact_persons",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Alias für zip_code",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="Deutschland", max_length=100)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="PublishJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "portal",
                    models.CharField(
                        choices=[
                            ("immoscout24", "ImmoScout24"),
                            ("immowelt", "Immowelt"),
                            ("ebay_kleinanzeigen", "eBay Kleinanzeigen"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("unpublished", "Unpublished"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "portal_property_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("portal_url", models.URLField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("unpublished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_jobs",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "publish_jobs",
                "indexes": [
                    models.Index(
                        fields=["property", "status"],
                        name="publish_job_propert_a00b90_idx",
                    ),
                    models.Index(
                        fields=["property", "portal"],
                        name="publish_job_propert_441664_idx",
                    ),
                    models.Index(
                        fields=["property", "created_at"],
                        name="publish_job_propert_96f047_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyMetricsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.IntegerField(default=0)),
                ("inquiries", models.IntegerField(default=0)),
                ("favorites", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("visits", models.IntegerField(default=0)),
                ("immoscout_views", models.IntegerField(default=0)),
                ("immoscout_inquiries", models.IntegerField(default=0)),
                ("immowelt_views", models.IntegerField(default=0)),
                ("immowelt_inquiries", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_snapshots",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_metrics_snapshots",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["property", "date"],
                        name="property_me_propert_60f8fd_idx",
                    ),
                    models.Index(fields=["date"], name="property_me_date_659336_idx"),
                ],
                "unique_together": {("property", "date")},
            },
        ),
        migrations.CreateModel(
            name="PropertyMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(
                        default=0, help_text="Total page views across all portals"
                    ),
                ),
                (
                    "total_inquiries",
                    models.IntegerField(default=0, help_text="Total contact requests"),
                ),
                (
                    "total_favorites",
                    models.IntegerField(default=0, help_text="Total saves/favorites"),
                ),
                (
                    "total_clicks",
                    models.IntegerField(default=0, help_text="Total clicks on listing"),
                ),
                (
                    "total_visits",
                    models.IntegerField(default=0, help_text="Total scheduled visits"),
                ),
                ("immoscout_views", models.IntegerField(default=0)),
                ("immoscout_inquiries", models.IntegerField(default=0)),
                ("immoscout_favorites", models.IntegerField(default=0)),
                ("immowelt_views", models.IntegerField(default=0)),
                ("immowelt_inquiries", models.IntegerField(default=0)),
                ("immowelt_favorites", models.IntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Inquiries/Views * 100",
                        max_digits=5,
                    ),
                ),
                (
                    "avg_view_duration",
                    models.IntegerField(
                        default=0, help_text="Average view duration in seconds"
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_metrics",
                "indexes": [
                    models.Index(
                        fields=["property"], name="property_me_propert_8de25e_idx"
                    ),
                    models.Index(
                        fields=["total_views"], name="property_me_total_v_01e386_idx"
                    ),
                    models.Index(
                        fields=["total_inquiries"],
                        name="property_me_total_i_3c7784_idx",
                    ),
                    models.Index(
                        fields=["last_synced_at"], name="property_me_last_sy_2b2cd9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="properties/images/%Y/%m/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "property_images",
                "indexes": [
                    models.Index(
                        fields=["property", "order"],
                        name="property_im_propert_3dfd5d_idx",
                    ),
                    models.Index(
                        fields=["property", "is_primary"],
                        name="property_im_propert_0ad054_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="properties/documents/%Y/%m/")),
                ("url", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("expose", "Exposé"),
                            ("floor_plan", "Grundriss"),
                            ("energy_certificate", "Energieausweis"),
                            ("contract", "Vertrag"),
                            ("protocol", "Protokoll"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "property_documents",
                "indexes": [
                    models.Index(
                        fields=["property", "document_type"],
                        name="property_do_propert_57960d_idx",
                    ),
                    models.Index(
                        fields=["property", "uploaded_at"],
                        name="property_do_propert_2f4177_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["tenant", "status"], name="properties_tenant__97a973_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["tenant", "property_type"], name="properties_tenant__859a58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["tenant", "price"], name="properties_tenant__727b9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["tenant", "created_at"], name="properties_tenant__6ec50b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exposeversion",
            index=models.Index(
                fields=["property", "status"], name="expose_vers_propert_625822_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exposeversion",
            index=models.Index(
                fields=["property", "created_at"], name="expose_vers_propert_6196cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exposeversion",
            index=models.Index(
                fields=["property", "version_number"],
                name="expose_vers_propert_d38941_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exposeversion",
            unique_together={("property", "version_number")},
        ),
    ]
