# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wip_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "boards",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#0A84FF", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_labels",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "task_labels",
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("done", "Done"),
                            ("blocked", "Blocked"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        max_length=30,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estimated_hours",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "actual_hours",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("property_id", models.UUIDField(blank=True, null=True)),
                (
                    "financing_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "story_points",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("ai_score", models.FloatField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("effort_score", models.FloatField(blank=True, null=True)),
                ("complexity", models.CharField(blank=True, max_length=50, null=True)),
                ("dependencies", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.board",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="tasks.tasklabel"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
        migrations.CreateModel(
            name="BoardStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("color", models.CharField(default="#8E8E93", max_length=7)),
                ("order", models.IntegerField(default=0)),
                (
                    "wip_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("is_terminal", models.BooleanField(default=False)),
                ("allow_from", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="tasks.board",
                    ),
                ),
            ],
            options={
                "db_table": "board_statuses",
            },
        ),
        migrations.AddField(
            model_name="board",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="tasks.project",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="accounts.tenant",
            ),
        ),
        migrations.CreateModel(
            name="TaskSubtask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("completed", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_subtasks",
                "indexes": [
                    models.Index(
                        fields=["task", "order"], name="task_subtas_task_id_e8f2e1_idx"
                    ),
                    models.Index(
                        fields=["task", "completed"],
                        name="task_subtas_task_id_dcb556_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tasks.taskcomment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_comments",
                "indexes": [
                    models.Index(
                        fields=["task", "timestamp"],
                        name="task_commen_task_id_d42b34_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "task_attachments",
                "indexes": [
                    models.Index(fields=["task"], name="task_attach_task_id_637c08_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "task_activities",
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="task_activi_task_id_fcfe49_idx",
                    ),
                    models.Index(
                        fields=["action"], name="task_activi_action_b4056e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "status"], name="tasks_tenant__aa382f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "priority"], name="tasks_tenant__47f3e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "assignee"], name="tasks_tenant__fbb5a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "project"], name="tasks_tenant__44587b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "board"], name="tasks_tenant__f279b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "due_date"], name="tasks_tenant__15004a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "created_at"], name="tasks_tenant__d09f73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant", "name"], name="projects_tenant__d3c87a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="boardstatus",
            index=models.Index(
                fields=["board", "order"], name="board_statu_board_i_db80cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardstatus",
            index=models.Index(
                fields=["board", "key"], name="board_statu_board_i_7f55bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardstatus",
            unique_together={("board", "key")},
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["tenant", "project"], name="boards_tenant__c14f79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["tenant", "name"], name="boards_tenant__d9ab27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="board",
            unique_together={("tenant", "name")},
        ),
    ]
