# Generated by Django 4.2.7 on 2026-01-08 21:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Property"),
                            ("fund", "Investment Fund"),
                            ("reit", "REIT"),
                            ("crowdfunding", "Crowdfunding"),
                            ("shares", "Property Shares"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("exited", "Exited"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("purchase_date", models.DateField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "target_roi",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target ROI in percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100")),
                            django.core.validators.MaxValueValidator(Decimal("1000")),
                        ],
                    ),
                ),
                (
                    "actual_roi",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Actual ROI in percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100")),
                            django.core.validators.MaxValueValidator(Decimal("1000")),
                        ],
                    ),
                ),
                (
                    "monthly_rental_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "occupancy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="Occupancy rate in percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investments",
            },
        ),
        migrations.CreateModel(
            name="InvestorPortfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_portfolios",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "investor_portfolios",
            },
        ),
        migrations.CreateModel(
            name="MarketplacePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "min_investment",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("expected_roi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("property_count", models.IntegerField(default=1)),
                ("property_types", models.JSONField(default=list)),
                ("max_investors", models.IntegerField()),
                ("current_investors", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_packages",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_packages",
            },
        ),
        migrations.CreateModel(
            name="InvestorReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.JSONField(default=dict)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="investor.investorportfolio",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_reports",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "investor_reports",
            },
        ),
        migrations.CreateModel(
            name="InvestmentIncome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("rental", "Rental Income"),
                            ("parking", "Parking"),
                            ("storage", "Storage"),
                            ("appreciation", "Property Appreciation"),
                            ("dividend", "Dividend"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income",
                        to="investor.investment",
                    ),
                ),
            ],
            options={
                "db_table": "investment_income",
            },
        ),
        migrations.CreateModel(
            name="InvestmentExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("property_tax", "Property Tax"),
                            ("insurance", "Insurance"),
                            ("management", "Management Fee"),
                            ("hoa", "HOA Fee"),
                            ("mortgage", "Mortgage Payment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="investor.investment",
                    ),
                ),
            ],
            options={
                "db_table": "investment_expenses",
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="investor.investorportfolio",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="related_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="accounts.tenant",
            ),
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "property_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_equity", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_income_ytd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total_expenses_ytd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "net_cashflow_ytd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "roi_ytd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "occupancy_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=5
                    ),
                ),
                (
                    "market_average_price_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "market_average_rent_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to="investor.investment",
                    ),
                ),
            ],
            options={
                "db_table": "performance_snapshots",
                "indexes": [
                    models.Index(
                        fields=["investment", "snapshot_date"],
                        name="performance_investm_e974a9_idx",
                    )
                ],
                "unique_together": {("investment", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="PackageReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="investor.marketplacepackage",
                    ),
                ),
            ],
            options={
                "db_table": "package_reservations",
                "indexes": [
                    models.Index(
                        fields=["package", "status"],
                        name="package_res_package_514965_idx",
                    ),
                    models.Index(
                        fields=["investor"], name="package_res_investo_bdd207_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="marketplacepackage",
            index=models.Index(
                fields=["tenant", "status"], name="marketplace_tenant__533728_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacepackage",
            index=models.Index(
                fields=["expires_at"], name="marketplace_expires_82aecf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investorreport",
            index=models.Index(
                fields=["tenant", "created_at"], name="investor_re_tenant__ed7a31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investorreport",
            index=models.Index(
                fields=["portfolio"], name="investor_re_portfol_b2180f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investorreport",
            index=models.Index(
                fields=["report_type"], name="investor_re_report__8662d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investorportfolio",
            index=models.Index(
                fields=["tenant", "owner"], name="investor_po_tenant__ae3a47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investorportfolio",
            index=models.Index(
                fields=["created_at"], name="investor_po_created_f35e43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentincome",
            index=models.Index(
                fields=["investment", "date"], name="investment__investm_4f1f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentincome",
            index=models.Index(
                fields=["income_type"], name="investment__income__0a05b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentexpense",
            index=models.Index(
                fields=["investment", "date"], name="investment__investm_f6a1c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentexpense",
            index=models.Index(
                fields=["expense_type"], name="investment__expense_27a3fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["tenant", "status"], name="investments_tenant__8ee9db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["portfolio"], name="investments_portfol_927df9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["related_property"], name="investments_related_d8a34a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["purchase_date"], name="investments_purchas_e92aac_idx"
            ),
        ),
    ]
