# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="documents.documentfolder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_folders",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "document_folders",
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_comments",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "document_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("edited", "Edited"),
                            ("deleted", "Deleted"),
                            ("downloaded", "Downloaded"),
                            ("viewed", "Viewed"),
                            ("shared", "Shared"),
                            ("commented", "Commented"),
                            ("moved", "Moved"),
                            ("renamed", "Renamed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_activities",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("expose", "Expose"),
                            ("energy_certificate", "Energy Certificate"),
                            ("floor_plan", "Floor Plan"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("presentation", "Presentation"),
                            ("spreadsheet", "Spreadsheet"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("legal", "Legal"),
                            ("marketing", "Marketing"),
                            ("technical", "Technical"),
                            ("financial", "Financial"),
                            ("administrative", "Administrative"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("team", "Team"),
                            ("restricted", "Restricted"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                ("search_vector", models.TextField(blank=True, null=True)),
                ("ocr_text", models.TextField(blank=True, null=True)),
                ("property_id", models.UUIDField(blank=True, null=True)),
                (
                    "property_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_id", models.UUIDField(blank=True, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=1)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.documentfolder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("file_url", models.URLField()),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("change_notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
                "indexes": [
                    models.Index(
                        fields=["document", "version_number"],
                        name="document_ve_documen_ff5d1a_idx",
                    ),
                    models.Index(
                        fields=["document", "created_at"],
                        name="document_ve_documen_97f3f0_idx",
                    ),
                ],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["tenant", "parent"], name="document_fo_tenant__166ead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["tenant", "name"], name="document_fo_tenant__f26bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentcomment",
            index=models.Index(
                fields=["tenant", "document_id", "-created_at"],
                name="document_co_tenant__fab9cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentactivity",
            index=models.Index(
                fields=["tenant", "document_id", "-timestamp"],
                name="document_ac_tenant__898644_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentactivity",
            index=models.Index(
                fields=["tenant", "action", "-timestamp"],
                name="document_ac_tenant__9e5561_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "type"], name="documents_tenant__05a721_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "status"], name="documents_tenant__ebc015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "uploaded_at"], name="documents_tenant__0df60d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "folder"], name="documents_tenant__ecd9ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "is_favorite"], name="documents_tenant__40851e_idx"
            ),
        ),
    ]
