# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key (e.g. 'custom_property_size')",
                        max_length=100,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("dropdown", "Dropdown"),
                            ("checkbox", "Checkbox"),
                            ("user", "User"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("task", "Task"), ("property", "Property")],
                        default="task",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("required", models.BooleanField(default=False)),
                ("default_value", models.TextField(blank=True, null=True)),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, help_text="Options for dropdown field"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_custom_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "custom_fields",
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.UUIDField()),
                ("value", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="custom_fields.customfield",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "custom_field_values",
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="custom_fiel_resourc_2377b2_idx",
                    ),
                    models.Index(
                        fields=["tenant", "resource_type"],
                        name="custom_fiel_tenant__de53d1_idx",
                    ),
                ],
                "unique_together": {("custom_field", "resource_type", "resource_id")},
            },
        ),
        migrations.AddIndex(
            model_name="customfield",
            index=models.Index(
                fields=["tenant", "resource_type", "is_active"],
                name="custom_fiel_tenant__823f76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfield",
            index=models.Index(fields=["key"], name="custom_fiel_key_81a9cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="customfield",
            unique_together={("tenant", "key", "resource_type")},
        ),
    ]
