# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "sla_type",
                    models.CharField(
                        choices=[
                            ("first_response", "First Response Time"),
                            ("resolution", "Resolution Time"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "time_limit_hours",
                    models.IntegerField(help_text="Time limit in hours"),
                ),
                ("applies_to", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_slas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slas",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "slas",
            },
        ),
        migrations.CreateModel(
            name="SLAInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("breached", "Breached"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paused_duration_seconds",
                    models.IntegerField(
                        default=0, help_text="Total paused duration in seconds"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("breached_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="sla.sla",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_instances",
                        to="tasks.task",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_instances",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "sla_instances",
                "indexes": [
                    models.Index(
                        fields=["sla", "status"], name="sla_instanc_sla_id_80d304_idx"
                    ),
                    models.Index(
                        fields=["task"], name="sla_instanc_task_id_32a2c7_idx"
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="sla_instanc_tenant__f1e0a3_idx",
                    ),
                    models.Index(
                        fields=["deadline"], name="sla_instanc_deadlin_aa2b7d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sla",
            index=models.Index(
                fields=["tenant", "is_active"], name="slas_tenant__bcb55b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sla",
            index=models.Index(fields=["sla_type"], name="slas_sla_typ_6894f1_idx"),
        ),
    ]
