# Generated by Django 5.2.7 on 2025-10-07 21:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='de', max_length=10)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('viewing', 'Viewing'), ('call', 'Call'), ('meeting', 'Meeting'), ('consultation', 'Consultation'), ('signing', 'Signing'), ('inspection', 'Inspection')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='draft', max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('property_id', models.UUIDField(blank=True, null=True)),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='app.appointment')),
            ],
            options={
                'db_table': 'attendees',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('land', 'Land'), ('office', 'Office'), ('retail', 'Retail'), ('industrial', 'Industrial')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(max_length=255)),
                ('living_area', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='app.property')),
            ],
            options={
                'db_table': 'contact_persons',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app.property')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='PropertyFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('energy_class', models.CharField(blank=True, max_length=10, null=True)),
                ('heating_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.property')),
            ],
            options={
                'db_table': 'property_features',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.property')),
            ],
            options={
                'db_table': 'property_images',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_hours', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('actual_hours', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('property_id', models.UUIDField(blank=True, null=True)),
                ('financing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.task')),
            ],
            options={
                'db_table': 'task_comments',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name der Organisation', max_length=255)),
                ('slug', models.SlugField(help_text='URL-freundlicher Identifier', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Hauptkontakt-Email', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Deutschland', max_length=100)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=50)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('max_users', models.IntegerField(default=5)),
                ('max_properties', models.IntegerField(default=10)),
                ('storage_limit_gb', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['email'], name='tenants_email_64287b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_labels', to='app.tenant')),
            ],
            options={
                'db_table': 'task_labels',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.tenant'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.tenant'),
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='app.documentfolder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='app.tenant')),
            ],
            options={
                'db_table': 'document_folders',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('contract', 'Contract'), ('expose', 'Expose'), ('energy_certificate', 'Energy Certificate'), ('floor_plan', 'Floor Plan'), ('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet'), ('pdf', 'PDF'), ('other', 'Other')], max_length=50)),
                ('category', models.CharField(choices=[('legal', 'Legal'), ('marketing', 'Marketing'), ('technical', 'Technical'), ('financial', 'Financial'), ('administrative', 'Administrative'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=50)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='private', max_length=20)),
                ('size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('property_id', models.UUIDField(blank=True, null=True)),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.documentfolder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.tenant')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(default='EUR', max_length=3)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('lead_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.tenant')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.tenant'),
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('agent', 'Agent'), ('viewer', 'Viewer')], default='agent', max_length=20)),
                ('can_manage_properties', models.BooleanField(default=True)),
                ('can_manage_documents', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='app.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('customer', 'Customer')], max_length=20)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'order'], name='property_im_propert_3dfd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'timestamp'], name='task_commen_task_id_d42b34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasklabel',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'status'], name='tasks_tenant__aa382f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'priority'], name='tasks_tenant__47f3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'assignee'], name='tasks_tenant__fbb5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'due_date'], name='tasks_tenant__15004a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'created_at'], name='tasks_tenant__d09f73_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'status'], name='properties_tenant__97a973_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'property_type'], name='properties_tenant__859a58_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'price'], name='properties_tenant__727b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'created_at'], name='properties_tenant__6ec50b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['tenant', 'parent'], name='document_fo_tenant__166ead_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['tenant', 'name'], name='document_fo_tenant__f26bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'type'], name='documents_tenant__05a721_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='documents_tenant__ebc015_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'uploaded_at'], name='documents_tenant__0df60d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'folder'], name='documents_tenant__ecd9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'is_favorite'], name='documents_tenant__40851e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'status'], name='contacts_tenant__5850a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'lead_score'], name='contacts_tenant__3bcf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'created_at'], name='contacts_tenant__1beb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'timestamp'], name='audit_logs_tenant__eb751d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'user', 'timestamp'], name='audit_logs_tenant__a23a86_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'resource_type', 'resource_id'], name='audit_logs_tenant__60c6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'start_datetime'], name='appointment_tenant__669f71_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status'], name='appointment_tenant__9998ad_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'type'], name='appointment_tenant__6c8cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['user', 'tenant'], name='tenant_user_user_id_6c8fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'role'], name='tenant_user_tenant__24f612_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant', 'role'], name='user_profil_tenant__9423f4_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='user_profil_tenant__7e264a_idx'),
        ),
    ]
