# Generated by Django 5.2.7 on 2025-10-07 21:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),  # Tenant model is now in accounts app
    ]

    operations = [
        # All models have been moved to their respective apps:
        # - Property, ContactPerson, Address, PropertyFeatures, PropertyImage -> properties app
        # - Task, TaskComment, TaskLabel -> tasks app  
        # - DocumentFolder, Document -> documents app
        # - Contact -> contacts app
        # - Appointment, Attendee -> appointments app
        # All CreateModel, AddField, AddIndex operations for these models are no longer needed
    ]
