# Generated by Django 5.2.7 on 2025-10-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # User model has been moved to accounts app, so this migration is no longer needed
        # The groups and user_permissions fields were never added to accounts.User
        # This is a no-op migration to maintain migration history
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
