# Generated by Django 5.2.7 on 2025-10-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_groups_remove_user_user_permissions'),
    ]

    operations = [
        # Tenant model has been moved to accounts app
        # All these fields are already in accounts/migrations/0001_initial.py
        # This is a no-op migration to maintain migration history
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
