# Generated by Django 5.2.7 on 2025-10-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tenant_currency_tenant_language_tenant_logo_url_and_more'),
    ]

    operations = [
        # Tenant model has been moved to accounts app
        # The tenant field in AuditLog already references accounts.tenant in 0001_initial
        # This is a no-op migration to maintain migration history
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
