# Generated by Django 4.2.7 on 2025-10-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_auditlog_tenant'),
    ]

    operations = [
        # Notification, NotificationPreference models have been moved to notifications app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
