# Generated by Django 5.2.7 on 2025-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notificationpreference_notification'),
    ]

    operations = [
        # Contact model has been moved to contacts app
        # All these operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
