# Generated by Django 5.2.7 on 2025-10-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Alias für zip_code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='Liste von Ausstattungsmerkmalen'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, help_text='Anzahl Schlafzimmer', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='coordinates_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='coordinates_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_consumption',
            field=models.IntegerField(blank=True, help_text='kWh/m²a', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, help_text='Anzahl Etagen', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='heating_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.IntegerField(blank=True, help_text='Grundstücksfläche in m²', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='price_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags für Kategorisierung'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.IntegerField(blank=True, help_text='Gesamtfläche in m²', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Deutschland', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, help_text='Anzahl Bäder', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_area',
            field=models.IntegerField(blank=True, help_text='Wohnfläche in m²', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, help_text='Anzahl Zimmer', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vorbereitung', 'Vorbereitung'), ('aktiv', 'Aktiv'), ('reserviert', 'Reserviert'), ('verkauft', 'Verkauft'), ('zurückgezogen', 'Zurückgezogen')], default='vorbereitung', max_length=50),
        ),
    ]
