# Generated by Django 5.2.7 on 2025-10-13 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_property_wizard_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='properties/documents/%Y/%m/')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('expose', 'Exposé'), ('floor_plan', 'Grundriss'), ('energy_certificate', 'Energieausweis'), ('contract', 'Vertrag'), ('protocol', 'Protokoll'), ('other', 'Sonstiges')], default='other', max_length=50)),
                ('size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_documents',
            },
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='properties/images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='property_im_propert_0ad054_idx'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.property'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['property', 'document_type'], name='property_do_propert_57960d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['property', 'uploaded_at'], name='property_do_propert_2f4177_idx'),
        ),
    ]
