# Generated by Django 5.2.7 on 2025-10-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_property_wizard_fields'),
    ]

    operations = [
        # Property, PropertyImage, PropertyDocument models have been moved to properties app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
