# Generated by Django 5.2.7 on 2025-10-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_property_media_upload'),
    ]

    operations = [
        # Document, DocumentVersion models have been moved to documents app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
