# Generated by Django 5.2.7 on 2025-10-14 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_property_media_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('team', 'Team'), ('restricted', 'Restricted')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('file_url', models.URLField()),
                ('file_size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app.document')),
            ],
            options={
                'db_table': 'document_versions',
                'indexes': [models.Index(fields=['document', 'version_number'], name='document_ve_documen_ff5d1a_idx'), models.Index(fields=['document', 'created_at'], name='document_ve_documen_97f3f0_idx')],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
