# Generated by Django 5.2.7 on 2025-10-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_document_versioning_and_search'),
    ]

    operations = [
        # SocialAccount, SocialPost models have been moved to communications app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
