# Generated by Django 5.2.7 on 2025-10-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_social_media_models'),
    ]

    operations = [
        # Permission, Role, FeatureFlag models have been moved to accounts app
        # All these models and fields are already in accounts/migrations/0001_initial.py
        # This is a no-op migration to maintain migration history
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
