# Generated by Django 4.2.7 on 2025-10-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_rbac_models'),
    ]

    operations = [
        # Tenant model has been moved to accounts app
        # The name field already has unique=True in accounts/migrations/0001_initial.py
        # This is a no-op migration to maintain migration history
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
