# Generated by Django 4.2.7 on 2025-10-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_rbac_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Name der Organisation', max_length=255, unique=True),
        ),
    ]
