# Generated by Django 5.2.7 on 2025-10-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='List of permission scopes'),
        ),
    ]
