# Generated by Django 5.2.7 on 2025-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tenantuser_scopes'),
    ]

    operations = [
        # User model has been moved to accounts app
        # The google_id field is already in accounts/migrations/0001_initial.py
        # This is a no-op migration to maintain migration history
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
