# Generated by Django 5.2.7 on 2025-10-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_google_id'),
    ]

    operations = [
        # Property, IntegrationSettings, ExposeVersion, PublishJob models have been moved to properties app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
