# Generated by Django 5.2.7 on 2025-10-16 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='co2_emissions',
            field=models.IntegerField(blank=True, help_text='CO₂-Emissionen in kg/m²a', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_certificate_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_certificate_type',
            field=models.CharField(blank=True, choices=[('bedarfsausweis', 'Bedarfsausweis'), ('verbrauchsausweis', 'Verbrauchsausweis')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_certificate_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_maps_api_key', models.TextField(blank=True, null=True)),
                ('immoscout_client_id', models.TextField(blank=True, null=True)),
                ('immoscout_client_secret', models.TextField(blank=True, null=True)),
                ('immoscout_access_token', models.TextField(blank=True, null=True)),
                ('immoscout_refresh_token', models.TextField(blank=True, null=True)),
                ('immoscout_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('immowelt_api_key', models.TextField(blank=True, null=True)),
                ('ebay_api_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_settings', to='app.tenant')),
            ],
            options={
                'db_table': 'integration_settings',
            },
        ),
        migrations.CreateModel(
            name='ExposeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('kauf', 'Kauf'), ('miete', 'Miete'), ('investor', 'Investor')], max_length=50)),
                ('tone', models.CharField(choices=[('neutral', 'Neutral'), ('elegant', 'Elegant'), ('kurz', 'Kurz')], max_length=50)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], max_length=10)),
                ('length', models.CharField(choices=[('short', 'Kurz'), ('standard', 'Standard'), ('long', 'Lang')], max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expose_versions', to='app.property')),
            ],
            options={
                'db_table': 'expose_versions',
                'indexes': [models.Index(fields=['property', 'status'], name='expose_vers_propert_625822_idx'), models.Index(fields=['property', 'created_at'], name='expose_vers_propert_6196cb_idx'), models.Index(fields=['property', 'version_number'], name='expose_vers_propert_d38941_idx')],
                'unique_together': {('property', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal', models.CharField(choices=[('immoscout24', 'ImmoScout24'), ('immowelt', 'Immowelt'), ('ebay_kleinanzeigen', 'eBay Kleinanzeigen')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('unpublished', 'Unpublished')], default='pending', max_length=20)),
                ('portal_property_id', models.CharField(blank=True, max_length=255, null=True)),
                ('portal_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_jobs', to='app.property')),
            ],
            options={
                'db_table': 'publish_jobs',
                'indexes': [models.Index(fields=['property', 'status'], name='publish_job_propert_a00b90_idx'), models.Index(fields=['property', 'portal'], name='publish_job_propert_441664_idx'), models.Index(fields=['property', 'created_at'], name='publish_job_propert_96f047_idx')],
            },
        ),
    ]
