# Generated by Django 5.2.7 on 2025-10-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_property_co2_emissions_and_more'),
    ]

    operations = [
        # StripeWebhookEvent, BillingAccount models have been moved to billing app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
