# Generated by Django 4.2.7 on 2025-10-17 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_property_co2_emissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'db_table': 'stripe_webhook_events',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['event_id'], name='stripe_webh_event_i_6b18cc_idx'), models.Index(fields=['event_type'], name='stripe_webh_event_t_2d6957_idx'), models.Index(fields=['processed_at'], name='stripe_webh_process_a44f0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('plan_key', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='active', max_length=50)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='app.tenant')),
            ],
            options={
                'db_table': 'billing_accounts',
                'indexes': [models.Index(fields=['tenant', 'plan_key'], name='billing_acc_tenant__98bbb6_idx'), models.Index(fields=['tenant', 'status'], name='billing_acc_tenant__648b03_idx'), models.Index(fields=['stripe_customer_id'], name='billing_acc_stripe__0ebfbc_idx'), models.Index(fields=['stripe_subscription_id'], name='billing_acc_stripe__f7f5da_idx')],
            },
        ),
    ]
