# Generated by Django 5.2.7 on 2025-10-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_stripewebhookevent_billingaccount'),
    ]

    operations = [
        # BillingAccount model has been moved to billing app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
