# Generated by Django 5.2.7 on 2025-10-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_stripewebhookevent_billingaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
