# Generated by Django 5.2.7 on 2025-10-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_billingaccount_trial_days_billingaccount_trial_end'),
    ]

    operations = [
        # Tenant model has been moved to accounts app
        # The plan field already has the correct choices in accounts/migrations/0001_initial.py
        # This is a no-op migration to maintain migration history
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
