# Generated by Django 5.2.7 on 2025-10-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_billingaccount_trial_days_billingaccount_trial_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
    ]
