# Generated by Django 5.2.7 on 2025-10-18 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_tenant_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('notification', 'Notification'), ('billing', 'Billing'), ('system', 'System'), ('welcome', 'Welcome'), ('trial_expired', 'Trial Expired'), ('test', 'Test')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='sent', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.notification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='app.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['tenant', 'sent_at'], name='email_logs_tenant__3d2487_idx'), models.Index(fields=['user', 'sent_at'], name='email_logs_user_id_b2f503_idx'), models.Index(fields=['email_type', 'sent_at'], name='email_logs_email_t_01afaa_idx'), models.Index(fields=['status', 'sent_at'], name='email_logs_status_00c463_idx'), models.Index(fields=['provider_name', 'sent_at'], name='email_logs_provide_20489e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('email_type', models.CharField(max_length=50)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('total_bounced', models.IntegerField(default=0)),
                ('first_used', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usage', to='app.tenant')),
            ],
            options={
                'db_table': 'email_template_usage',
                'ordering': ['-last_used'],
                'unique_together': {('tenant', 'template_name')},
            },
        ),
    ]
