# Generated by Django 4.2.7 on 2025-12-09 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_social_hub_enhancements"),
    ]

    operations = [
        # Property, PropertyMetrics, PropertyMetricsSnapshot models have been moved to properties app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
