# Generated by Django 4.2.7 on 2025-12-09 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_social_hub_enhancements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("akquise", "Akquise"),
                    ("vorbereitung", "Vorbereitung"),
                    ("aktiv", "Aktiv"),
                    ("reserviert", "Reserviert"),
                    ("verkauft", "Verkauft"),
                    ("zurückgezogen", "Zurückgezogen"),
                ],
                default="vorbereitung",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PropertyMetricsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.IntegerField(default=0)),
                ("inquiries", models.IntegerField(default=0)),
                ("favorites", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("visits", models.IntegerField(default=0)),
                ("immoscout_views", models.IntegerField(default=0)),
                ("immoscout_inquiries", models.IntegerField(default=0)),
                ("immowelt_views", models.IntegerField(default=0)),
                ("immowelt_inquiries", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_snapshots",
                        to="app.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_metrics_snapshots",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["property", "date"],
                        name="property_me_propert_60f8fd_idx",
                    ),
                    models.Index(fields=["date"], name="property_me_date_659336_idx"),
                ],
                "unique_together": {("property", "date")},
            },
        ),
        migrations.CreateModel(
            name="PropertyMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(
                        default=0, help_text="Total page views across all portals"
                    ),
                ),
                (
                    "total_inquiries",
                    models.IntegerField(default=0, help_text="Total contact requests"),
                ),
                (
                    "total_favorites",
                    models.IntegerField(default=0, help_text="Total saves/favorites"),
                ),
                (
                    "total_clicks",
                    models.IntegerField(default=0, help_text="Total clicks on listing"),
                ),
                (
                    "total_visits",
                    models.IntegerField(default=0, help_text="Total scheduled visits"),
                ),
                ("immoscout_views", models.IntegerField(default=0)),
                ("immoscout_inquiries", models.IntegerField(default=0)),
                ("immoscout_favorites", models.IntegerField(default=0)),
                ("immowelt_views", models.IntegerField(default=0)),
                ("immowelt_inquiries", models.IntegerField(default=0)),
                ("immowelt_favorites", models.IntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Inquiries/Views * 100",
                        max_digits=5,
                    ),
                ),
                (
                    "avg_view_duration",
                    models.IntegerField(
                        default=0, help_text="Average view duration in seconds"
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="app.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_metrics",
                "indexes": [
                    models.Index(
                        fields=["property"], name="property_me_propert_8de25e_idx"
                    ),
                    models.Index(
                        fields=["total_views"], name="property_me_total_v_01e386_idx"
                    ),
                    models.Index(
                        fields=["total_inquiries"],
                        name="property_me_total_i_3c7784_idx",
                    ),
                    models.Index(
                        fields=["last_synced_at"], name="property_me_last_sy_2b2cd9_idx"
                    ),
                ],
            },
        ),
    ]
