# Generated by Django 4.2.7 on 2025-12-09 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_contact_lead_score_details"),
        ("app", "0021_add_property_metrics"),
    ]

    operations = []
