# Generated by Django 5.2.7 on 2025-10-18 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_add_last_message_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='app.message')),
            ],
            options={
                'db_table': 'message_mentions',
                'indexes': [models.Index(fields=['message', 'created_at'], name='message_men_message_dcfc4b_idx'), models.Index(fields=['mentioned_user', 'created_at'], name='message_men_mention_5f3075_idx')],
                'unique_together': {('message', 'mentioned_user')},
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_reactions',
                'indexes': [models.Index(fields=['message', 'reaction_type'], name='message_rea_message_57565e_idx'), models.Index(fields=['user', 'created_at'], name='message_rea_user_id_096006_idx')],
                'unique_together': {('message', 'user', 'reaction_type')},
            },
        ),
    ]
