# Generated by Django 4.2.7 on 2025-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_merge_20251209_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="additional_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional contact information like birth_date, source, etc.",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.JSONField(
                blank=True, default=dict, help_text="Contact address details"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about contact", null=True
            ),
        ),
    ]
