# Generated by Django 4.2.7 on 2025-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_merge_20251209_2030"),
    ]

    operations = [
        # Contact model has been moved to contacts app
        # All these operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
