# Generated by Django 5.2.7 on 2025-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_mentions_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for duplicate detection', max_length=64),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file_hash'], name='message_att_file_ha_919f29_idx'),
        ),
    ]
