# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_add_file_hash_to_attachment'),
    ]

    operations = [
        # Create Sprint model
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenant')),
            ],
            options={
                'db_table': 'sprints',
            },
        ),
        
        # Create TaskSubtask model
        migrations.CreateModel(
            name='TaskSubtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='app.task')),
            ],
            options={
                'db_table': 'task_subtasks',
                'ordering': ['order'],
            },
        ),
        
        # Create TaskAttachment model
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'task_attachments',
            },
        ),
        
        # Create TaskWatcher model
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'task_watchers',
            },
        ),
        
        # Add new fields to Task model
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sprint'),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_by_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='epic_link',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_type',
            field=models.CharField(choices=[('task', 'Task'), ('story', 'Story'), ('bug', 'Bug'), ('epic', 'Epic')], default='task', max_length=50),
        ),
        
        # Add many-to-many relationship for labels
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='app.tasklabel'),
        ),
        
        # Add unique constraint for TaskWatcher
        migrations.AlterUniqueTogether(
            name='taskwatcher',
            unique_together={('task', 'user')},
        ),
        
        # Add indexes for performance
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant', 'status'], name='sprints_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant', 'start_date'], name='sprints_tenant_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubtask',
            index=models.Index(fields=['task', 'order'], name='task_subtasks_task_order_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task', 'uploaded_at'], name='task_attachments_task_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='taskwatcher',
            index=models.Index(fields=['task', 'added_at'], name='task_watchers_task_added_idx'),
        ),
    ]
