# Generated by Django 4.2.7 on 2025-12-12 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_communications"),
    ]

    operations = [
        # Attachment, Channel, ChannelMembership, Message, Reaction, ResourceLink, Team models have been moved to communications app
        # All RenameIndex operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
