# Generated by Django 4.2.7 on 2025-12-12 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_add_task_resource"),
        (
            "app",
            "0025_rename_att_tenant_message_idx_attachments_tenant__e5995a_idx_and_more",
        ),
    ]

    operations = []
