# Generated by Django 5.2.7 on 2025-10-18 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_add_kanban_features'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sprint',
            name='sprints_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sprint',
            name='sprints_tenant_start_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskattachment',
            name='task_attachments_task_uploaded_idx',
        ),
        migrations.RemoveIndex(
            model_name='tasksubtask',
            name='task_subtasks_task_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskwatcher',
            name='task_watchers_task_added_idx',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasksubtask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskwatcher',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
