# Generated by Django 4.2.7 on 2025-12-12 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_merge_20251212_2301"),
    ]

    operations = [
        # Task, TaskActivity, TaskAttachment, TaskSubtask, Board, BoardStatus, Project models have been moved to tasks app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
