# Generated by Django 4.2.7 on 2025-12-12 22:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_merge_20251212_2301"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wip_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "boards",
            },
        ),
        migrations.CreateModel(
            name="BoardStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("color", models.CharField(default="#8E8E93", max_length=7)),
                ("order", models.IntegerField(default=0)),
                (
                    "wip_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("is_terminal", models.BooleanField(default=False)),
                ("allow_from", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "board_statuses",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#0A84FF", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_activities",
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_attachments",
            },
        ),
        migrations.CreateModel(
            name="TaskSubtask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("completed", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "task_subtasks",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="ai_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="complexity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="effort_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="impact_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="app.tasklabel"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="story_points",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                    ("blocked", "Blocked"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="todo",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="app.project",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="app.board",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "project"], name="tasks_tenant__44587b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["tenant", "board"], name="tasks_tenant__f279b9_idx"
            ),
        ),
        migrations.AddField(
            model_name="tasksubtask",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasksubtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="app.task",
            ),
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app.task",
            ),
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskactivity",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="app.task",
            ),
        ),
        migrations.AddField(
            model_name="taskactivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="app.tenant",
            ),
        ),
        migrations.AddField(
            model_name="boardstatus",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="app.board",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="app.project",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="app.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="tasksubtask",
            index=models.Index(
                fields=["task", "order"], name="task_subtas_task_id_e8f2e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasksubtask",
            index=models.Index(
                fields=["task", "completed"], name="task_subtas_task_id_dcb556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskattachment",
            index=models.Index(fields=["task"], name="task_attach_task_id_637c08_idx"),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(
                fields=["task", "created_at"], name="task_activi_task_id_fcfe49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(fields=["action"], name="task_activi_action_b4056e_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant", "name"], name="projects_tenant__d3c87a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="boardstatus",
            index=models.Index(
                fields=["board", "order"], name="board_statu_board_i_db80cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardstatus",
            index=models.Index(
                fields=["board", "key"], name="board_statu_board_i_7f55bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardstatus",
            unique_together={("board", "key")},
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["tenant", "project"], name="boards_tenant__c14f79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["tenant", "name"], name="boards_tenant__d9ab27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="board",
            unique_together={("tenant", "name")},
        ),
    ]
