# Generated by Django 4.2.7 on 2025-12-13 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_board_boardstatus_project_taskactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, help_text='City, town, or village name', max_length=200)),
                ('state', models.CharField(blank=True, help_text='State/Bundesland (e.g., Bayern, Berlin)', max_length=100)),
                ('country', models.CharField(default='Deutschland', help_text='Country name', max_length=100)),
                ('postal_code_start', models.CharField(blank=True, db_index=True, help_text='Start of postal code range (e.g., 80000)', max_length=10)),
                ('postal_code_end', models.CharField(blank=True, help_text='End of postal code range (e.g., 81999)', max_length=10)),
                ('base_price_per_sqm', models.DecimalField(decimal_places=2, help_text='Base market price per square meter in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_premium_location', models.BooleanField(default=False, help_text='Premium location with +20% adjustment')),
                ('is_suburban', models.BooleanField(default=False, help_text='Suburban location with -5% adjustment')),
                ('population', models.IntegerField(blank=True, help_text='Population size', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location_type', models.CharField(choices=[('metropolis', 'Metropole (>1M)'), ('city', 'Großstadt (>100k)'), ('town', 'Stadt (>10k)'), ('village', 'Dorf/Gemeinde (<10k)')], default='city', help_text='Type of location', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this location is active for AVM calculations')),
            ],
            options={
                'verbose_name': 'Location Market Data',
                'verbose_name_plural': 'Location Market Data',
                'db_table': 'location_market_data',
                'ordering': ['-population', 'city'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='location_ma_city_9bf1d3_idx'), models.Index(fields=['postal_code_start', 'postal_code_end'], name='location_ma_postal__ac65e1_idx'), models.Index(fields=['-population'], name='location_ma_populat_39466b_idx')],
            },
        ),
    ]
