# Generated by Django 4.2.7 on 2025-12-12 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_board_boardstatus_project_taskactivity_and_more"),
    ]

    operations = [
        # LocationMarketData model has been moved to locations app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
