# Generated by Django 4.2.7 on 2025-12-13 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_locationmarketdata"),
    ]

    operations = [
        # DocumentComment, DocumentActivity models have been moved to documents app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
