# Generated by Django 5.2.7 on 2025-10-20 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_task_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('maintenance_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('management_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_data', to='app.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_properties', to='app.tenant')),
            ],
            options={
                'db_table': 'investor_properties',
                'indexes': [models.Index(fields=['tenant', 'purchase_date'], name='investor_pr_tenant__99bad6_idx'), models.Index(fields=['tenant', 'current_value'], name='investor_pr_tenant__d228d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_reports', to='app.tenant')),
            ],
            options={
                'db_table': 'investor_reports',
                'indexes': [models.Index(fields=['tenant', 'report_type'], name='investor_re_tenant__7e4c09_idx'), models.Index(fields=['tenant', 'generated_at'], name='investor_re_tenant__e8972b_idx'), models.Index(fields=['tenant', 'status'], name='investor_re_tenant__05dc16_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_investors', models.IntegerField()),
                ('current_investors', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold_out', 'Sold Out'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('property_count', models.IntegerField()),
                ('property_types', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('properties', models.ManyToManyField(blank=True, related_name='marketplace_packages', to='app.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_packages', to='app.tenant')),
            ],
            options={
                'db_table': 'marketplace_packages',
                'indexes': [models.Index(fields=['tenant', 'status'], name='marketplace_tenant__533728_idx'), models.Index(fields=['tenant', 'expires_at'], name='marketplace_tenant__2646f2_idx'), models.Index(fields=['tenant', 'expected_roi'], name='marketplace_tenant__08e411_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('property_sale', 'Property Sale'), ('property_rent', 'Property Rent'), ('market_update', 'Market Update'), ('company_news', 'Company News'), ('investment_tip', 'Investment Tip'), ('general', 'General')], max_length=50)),
                ('content_template', models.TextField()),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_templates', to='app.tenant')),
            ],
            options={
                'db_table': 'social_templates',
                'indexes': [models.Index(fields=['tenant', 'template_type'], name='social_temp_tenant__bcf3fd_idx'), models.Index(fields=['tenant', 'is_active'], name='social_temp_tenant__f18b05_idx'), models.Index(fields=['tenant', 'created_at'], name='social_temp_tenant__4f476f_idx')],
            },
        ),
    ]
