# Generated by Django 4.2.7 on 2025-12-13 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_locationmarketdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_comments",
                        to="app.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "document_comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "document_id", "-created_at"],
                        name="document_co_tenant__fab9cb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("edited", "Edited"),
                            ("deleted", "Deleted"),
                            ("downloaded", "Downloaded"),
                            ("viewed", "Viewed"),
                            ("shared", "Shared"),
                            ("commented", "Commented"),
                            ("moved", "Moved"),
                            ("renamed", "Renamed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_activities",
                        to="app.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "document_id", "-timestamp"],
                        name="document_ac_tenant__898644_idx",
                    ),
                    models.Index(
                        fields=["tenant", "action", "-timestamp"],
                        name="document_ac_tenant__9e5561_idx",
                    ),
                ],
            },
        ),
    ]
