# Generated by Django 4.2.7 on 2025-12-13 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_documentcomment_documentactivity"),
    ]

    operations = [
        # Investment, InvestorPortfolio, InvestmentIncome, InvestmentExpense, PerformanceSnapshot, MarketplacePackage, PackageReservation, InvestorReport models have been moved to investor app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
