# Generated by Django 5.2.7 on 2025-10-21 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_investorproperty_investorreport_marketplacepackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('management', 'Management'), ('insurance', 'Insurance'), ('property_tax', 'Property Tax'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='app.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='app.tenant')),
            ],
            options={
                'db_table': 'cost_records',
                'indexes': [models.Index(fields=['tenant', 'record_date'], name='cost_record_tenant__a52db5_idx'), models.Index(fields=['property', 'record_date'], name='cost_record_propert_9a6011_idx'), models.Index(fields=['tenant', 'category', 'record_date'], name='cost_record_tenant__4dc4d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=255)),
                ('investor_email', models.EmailField(max_length=254)),
                ('investor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contact_preference', models.CharField(default='email', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.marketplacepackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_reservations', to='app.tenant')),
            ],
            options={
                'db_table': 'package_reservations',
                'indexes': [models.Index(fields=['tenant', 'status'], name='package_res_tenant__79a0c4_idx'), models.Index(fields=['package', 'status'], name='package_res_package_514965_idx'), models.Index(fields=['tenant', 'reserved_at'], name='package_res_tenant__cd4687_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('total_portfolio_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cashflow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vacancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset_count', models.IntegerField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('portfolio_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='app.tenant')),
            ],
            options={
                'db_table': 'performance_snapshots',
                'indexes': [models.Index(fields=['tenant', 'snapshot_date'], name='performance_tenant__d89326_idx'), models.Index(fields=['tenant', 'created_at'], name='performance_tenant__5feb7f_idx')],
                'unique_together': {('tenant', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='ROISimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scenario', models.CharField(choices=[('optimistic', 'Optimistic'), ('realistic', 'Realistic'), ('pessimistic', 'Pessimistic'), ('custom', 'Custom')], max_length=50)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term_years', models.IntegerField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maintenance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('property_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insurance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('management_fee_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_cashflow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_cashflow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_return_5y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_return_10y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('break_even_months', models.IntegerField()),
                ('net_present_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('internal_rate_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cash_on_cash_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roi_projection', models.JSONField(blank=True, default=list)),
                ('scenarios', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_simulations', to='app.tenant')),
            ],
            options={
                'db_table': 'roi_simulations',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='roi_simulat_tenant__cdfe90_idx'), models.Index(fields=['tenant', 'scenario'], name='roi_simulat_tenant__e10fe9_idx'), models.Index(fields=['tenant', 'name'], name='roi_simulat_tenant__efc2e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='VacancyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('vacancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacant_units', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=1)),
                ('vacancy_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_records', to='app.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_records', to='app.tenant')),
            ],
            options={
                'db_table': 'vacancy_records',
                'indexes': [models.Index(fields=['tenant', 'record_date'], name='vacancy_rec_tenant__13a6c2_idx'), models.Index(fields=['property', 'record_date'], name='vacancy_rec_propert_79924f_idx'), models.Index(fields=['tenant', 'property', 'record_date'], name='vacancy_rec_tenant__8f68d0_idx')],
            },
        ),
    ]
