# Generated by Django 4.2.7 on 2026-01-03 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_add_investor_models"),
    ]

    operations = [
        # AutomationRule, AutomationLog models have been moved to automation app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
