# Generated by Django 4.2.7 on 2026-01-03 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0031_add_automation_models"),
    ]

    operations = [
        # Workflow, WorkflowInstance models have been moved to workflow app
        # All operations are no longer needed
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
