# Generated by Django 4.2.7 on 2024-01-15 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_costrecord_packagereservation_performancesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_users_count', models.IntegerField(default=0, help_text='Number of active users')),
                ('storage_bytes_used', models.BigIntegerField(default=0, help_text='Storage used in bytes')),
                ('properties_count', models.IntegerField(default=0, help_text='Number of properties')),
                ('documents_count', models.IntegerField(default=0, help_text='Number of documents')),
                ('last_reconciled_at', models.DateTimeField(blank=True, help_text='Last storage reconciliation', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='app.tenant')),
            ],
            options={
                'db_table': 'tenant_usage',
            },
        ),
        migrations.CreateModel(
            name='PropertyViewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_fingerprint', models.CharField(blank=True, help_text='Anonymous viewer identifier', max_length=64, null=True)),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API'), ('email', 'Email'), ('social', 'Social Media')], default='web', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='app.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_view_events', to='app.tenant')),
            ],
            options={
                'db_table': 'property_view_events',
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('email', 'Email'), ('phone', 'Phone'), ('social', 'Social Media'), ('portal', 'Portal')], default='web', max_length=50)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('viewing', 'Viewing Request'), ('price', 'Price Inquiry'), ('financing', 'Financing Question'), ('other', 'Other')], default='general', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_inquiries', to='app.contact')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_events', to='app.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_inquiry_events', to='app.tenant')),
            ],
            options={
                'db_table': 'property_inquiry_events',
            },
        ),
        migrations.AddIndex(
            model_name='tenantusage',
            index=models.Index(fields=['tenant', 'updated_at'], name='tenant_usage_tenant_id_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewevent',
            index=models.Index(fields=['tenant', 'property', 'created_at'], name='property_view_events_tenant_id_property_id_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewevent',
            index=models.Index(fields=['tenant', 'created_at'], name='property_view_events_tenant_id_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewevent',
            index=models.Index(fields=['property', 'created_at'], name='property_view_events_property_id_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiryevent',
            index=models.Index(fields=['tenant', 'property', 'created_at'], name='property_inquiry_events_tenant_id_property_id_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiryevent',
            index=models.Index(fields=['tenant', 'created_at'], name='property_inquiry_events_tenant_id_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiryevent',
            index=models.Index(fields=['property', 'created_at'], name='property_inquiry_events_property_id_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiryevent',
            index=models.Index(fields=['contact', 'created_at'], name='property_inquiry_events_contact_id_created_at_idx'),
        ),
    ]
