# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0033_fix_workflow_tables"),
    ]

    operations = [
        # Address, Appointment, Attendee, Attachment models have been moved to properties/appointments/communications apps
        # These operations are no longer needed
        # AuditLog model has been moved to common app
        # These operations are no longer needed
        # AutomationLog and AutomationRule models have been moved to automation app
        # These operations are no longer needed
        # BillingAccount model has been moved to billing app
        # This operation is no longer needed
        # Board and BoardStatus models have been moved to tasks app
        # These operations are no longer needed
        # Channel and ChannelMembership models have been moved to communications app
        # These operations are no longer needed
        # Contact and ContactPerson models have been moved to contacts/properties apps
        # These operations are no longer needed
        # Document models have been moved to documents app
        # These operations are no longer needed
        # ExposeVersion model has been moved to properties app
        # These operations are no longer needed
        # FeatureFlag model has been moved to accounts app
        # These operations are no longer needed
        # IntegrationSettings model has been moved to properties app
        # These operations are no longer needed
        # Investment models have been moved to investor app
        # These operations are no longer needed
        # LocationMarketData model has been moved to locations app
        # This operation is no longer needed
        # Message model has been moved to communications app
        # These operations are no longer needed
        # Notification models have been moved to notifications app
        # These operations are no longer needed
        # PackageReservation and PerformanceSnapshot models have been moved to investor app
        # These operations are no longer needed
        # Project model has been moved to tasks app
        # This operation is no longer needed
        # Property models have been moved to properties app
        # These operations are no longer needed
        # Reaction and ResourceLink models have been moved to communications app
        # These operations are no longer needed
        # Role model has been moved to accounts app
        # These operations are no longer needed
        # SocialAccount and SocialPost models have been moved to communications app
        # These operations are no longer needed
        # StripeWebhookEvent model has been moved to billing app
        # This operation is no longer needed
        # Task models have been moved to tasks app
        # These operations are no longer needed
        # Team model has been moved to communications app
        # These operations are no longer needed
        # TenantUser and UserProfile models have been moved to accounts app
        # These operations are no longer needed
        # Workflow and WorkflowInstance models have been moved to workflow app
        # These operations are no longer needed
        # All DeleteModel operations for moved models have been removed above
    ]
