# Generated by Django 5.2.7 on 2025-10-21 16:24

import app.db.models.employee_document
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_add_usage_tracking_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template-Name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Beschreibung', null=True)),
                ('template_content', models.TextField(help_text='Template-Inhalt (HTML/Markdown)')),
                ('variables', models.JSONField(default=list, help_text="Verfügbare Variablen (z.B. ['employee_name', 'start_date'])")),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Standard-Template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name des Dokumententyps', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Beschreibung', null=True)),
                ('requires_signature', models.BooleanField(default=False, help_text='Erfordert Signatur')),
                ('requires_expiry_date', models.BooleanField(default=False, help_text='Erfordert Ablaufdatum')),
                ('default_validity_days', models.IntegerField(blank=True, help_text='Standard-Gültigkeitsdauer in Tagen', null=True)),
                ('allowed_extensions', models.JSONField(default=list, help_text="Erlaubte Dateierweiterungen (z.B. ['pdf', 'doc', 'docx'])")),
                ('max_file_size_mb', models.IntegerField(default=10, help_text='Maximale Dateigröße in MB')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(help_text='Mitarbeiternummer', max_length=20, unique=True)),
                ('department', models.CharField(choices=[('management', 'Management'), ('sales', 'Verkauf'), ('marketing', 'Marketing'), ('admin', 'Administration'), ('it', 'IT'), ('hr', 'Personalwesen'), ('finance', 'Finanzen'), ('legal', 'Recht'), ('other', 'Sonstiges')], default='sales', max_length=50)),
                ('position', models.CharField(choices=[('ceo', 'Geschäftsführer'), ('manager', 'Manager'), ('senior_agent', 'Senior Makler'), ('agent', 'Makler'), ('junior_agent', 'Junior Makler'), ('assistant', 'Assistent'), ('intern', 'Praktikant'), ('other', 'Sonstiges')], default='agent', max_length=50)),
                ('employment_type', models.CharField(choices=[('full_time', 'Vollzeit'), ('part_time', 'Teilzeit'), ('contract', 'Vertrag'), ('intern', 'Praktikum'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('start_date', models.DateField(help_text='Einstellungsdatum')),
                ('end_date', models.DateField(blank=True, help_text='Austrittsdatum', null=True)),
                ('work_email', models.EmailField(blank=True, help_text='Arbeits-E-Mail', max_length=254, null=True)),
                ('work_phone', models.CharField(blank=True, help_text='Arbeits-Telefon', max_length=50, null=True)),
                ('office_location', models.CharField(blank=True, help_text='Bürostandort', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_on_leave', models.BooleanField(default=False)),
                ('leave_start', models.DateField(blank=True, null=True)),
                ('leave_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Grundgehalt', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary_type', models.CharField(choices=[('monthly', 'Monatlich'), ('annual', 'Jährlich'), ('hourly', 'Stündlich')], default='monthly', max_length=20)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Provisionssatz in Prozent', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('commission_type', models.CharField(choices=[('percentage', 'Prozent'), ('fixed', 'Fester Betrag'), ('tiered', 'Gestaffelt')], default='percentage', max_length=20)),
                ('commission_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mindestumsatz für Provision', max_digits=10)),
                ('monthly_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monatlicher Bonus', max_digits=10)),
                ('annual_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Jährlicher Bonus', max_digits=10)),
                ('car_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fahrzeugzuschuss', max_digits=8)),
                ('phone_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Telefonzuschuss', max_digits=6)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sonstige Zuschüsse', max_digits=8)),
                ('tax_class', models.CharField(default='1', help_text='Steuerklasse', max_length=10)),
                ('social_security_number', models.CharField(blank=True, help_text='Sozialversicherungsnummer', max_length=20, null=True)),
                ('effective_from', models.DateField(help_text='Gültig ab')),
                ('effective_until', models.DateField(blank=True, help_text='Gültig bis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_compensations',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Dokumenttitel', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Beschreibung', null=True)),
                ('version', models.CharField(default='1.0', help_text='Version', max_length=20)),
                ('file_name', models.CharField(help_text='Original-Dateiname', max_length=255)),
                ('file_path', models.FileField(help_text='Datei', upload_to=app.db.models.employee_document.employee_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('file_size', models.BigIntegerField(help_text='Dateigröße in Bytes')),
                ('mime_type', models.CharField(help_text='MIME-Typ', max_length=100)),
                ('valid_from', models.DateField(default=django.utils.timezone.now, help_text='Gültig ab')),
                ('valid_until', models.DateField(blank=True, help_text='Gültig bis', null=True)),
                ('sign_status', models.CharField(choices=[('pending', 'Ausstehend'), ('signed', 'Signiert'), ('expired', 'Abgelaufen'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, help_text='Signiert am', null=True)),
                ('signature_notes', models.TextField(blank=True, help_text='Signatur-Notizen', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Vertraulich')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('sent', 'Gesendet'), ('resent', 'Erneut gesendet'), ('accepted', 'Angenommen'), ('expired', 'Abgelaufen'), ('cancelled', 'Storniert')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Zusätzliche Details', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invitation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('car_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('phone_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('income_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('social_security_employee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('health_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pension_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unemployment_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('working_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_entries',
                'ordering': ['employee__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('period_start', models.DateField(help_text='Periode von')),
                ('period_end', models.DateField(help_text='Periode bis')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('approved', 'Genehmigt'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_social_security', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('employee_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen', null=True)),
            ],
            options={
                'db_table': 'payroll_runs',
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='E-Mail-Adresse des eingeladenen Benutzers', max_length=254)),
                ('first_name', models.CharField(help_text='Vorname', max_length=100)),
                ('last_name', models.CharField(help_text='Nachname', max_length=100)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('agent', 'Agent'), ('viewer', 'Viewer')], default='agent', help_text='Rolle', max_length=20)),
                ('token', models.CharField(help_text='Einladungstoken', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Ablaufdatum')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Angenommen'), ('expired', 'Abgelaufen'), ('cancelled', 'Storniert')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Angenommen am', null=True)),
                ('message', models.TextField(blank=True, help_text='Persönliche Nachricht', null=True)),
                ('department', models.CharField(blank=True, help_text='Abteilung', max_length=50, null=True)),
                ('position', models.CharField(blank=True, help_text='Position', max_length=100, null=True)),
                ('permissions', models.JSONField(default=dict, help_text='Spezifische Berechtigungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='propertyinquiryevent',
            new_name='property_in_tenant__77cc45_idx',
            old_name='property_inquiry_events_tenant_id_property_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyinquiryevent',
            new_name='property_in_tenant__c66db0_idx',
            old_name='property_inquiry_events_tenant_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyinquiryevent',
            new_name='property_in_propert_819771_idx',
            old_name='property_inquiry_events_property_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyinquiryevent',
            new_name='property_in_contact_930fd2_idx',
            old_name='property_inquiry_events_contact_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyviewevent',
            new_name='property_vi_tenant__b8474a_idx',
            old_name='property_view_events_tenant_id_property_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyviewevent',
            new_name='property_vi_tenant__d03b41_idx',
            old_name='property_view_events_tenant_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyviewevent',
            new_name='property_vi_propert_cc9989_idx',
            old_name='property_view_events_property_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantusage',
            new_name='tenant_usag_tenant__97ac4d_idx',
            old_name='tenant_usage_tenant_id_updated_at_idx',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tenants/{tenant_id}/properties/{property_id}/images/'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_document_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='app.tenant'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_document_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='app.tenant'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='app.documenttype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='app.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_compensations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='app.employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.documenttype'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='app.tenant'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='app.employee'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='app.tenant'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.payrollrun'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.tenant'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitationlog',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.userinvitation'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['tenant', 'is_active'], name='document_ty_tenant__c0de2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['tenant', 'document_type'], name='document_te_tenant__3e881b_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='document_te_tenant__d862c7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='employees_tenant__6ef9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'department'], name='employees_tenant__ac492f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'position'], name='employees_tenant__5361a7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='employees_employe_68f2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensation',
            index=models.Index(fields=['employee', 'effective_from'], name='employee_co_employe_293815_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['tenant', 'employee'], name='employee_do_tenant__62c226_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['tenant', 'document_type'], name='employee_do_tenant__650ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['tenant', 'sign_status'], name='employee_do_tenant__1590c9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'document_type'], name='employee_do_employe_a1189d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['valid_until'], name='employee_do_valid_u_bc907f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['tenant', 'period'], name='payroll_run_tenant__eed8df_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['tenant', 'status'], name='payroll_run_tenant__da031f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['period'], name='payroll_run_period_f4f84a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('tenant', 'period')},
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['payroll_run', 'employee'], name='payroll_ent_payroll_2429d0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['employee'], name='payroll_ent_employe_27018e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together={('payroll_run', 'employee')},
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['tenant', 'status'], name='user_invita_tenant__8a6758_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['email'], name='user_invita_email_abd596_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['token'], name='user_invita_token_59cb54_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['expires_at'], name='user_invita_expires_26d966_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationlog',
            index=models.Index(fields=['invitation', 'action'], name='invitation__invitat_5d29fd_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationlog',
            index=models.Index(fields=['created_at'], name='invitation__created_9c10cc_idx'),
        ),
    ]
