# Generated by Django 5.2.7 on 2025-10-22 10:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_add_tiktok_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Datum')),
                ('check_in', models.TimeField(blank=True, help_text='Check-in Zeit', null=True)),
                ('check_out', models.TimeField(blank=True, help_text='Check-out Zeit', null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, help_text='Gearbeitete Stunden', max_digits=4, null=True)),
                ('location', models.CharField(blank=True, help_text='Arbeitsort', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notizen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.tenant')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-check_in'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='attendance_tenant__85d3d6_idx'), models.Index(fields=['employee', 'date'], name='attendance_employe_c9bb2b_idx'), models.Index(fields=['date'], name='attendance_date_d460ba_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Datum der Ausgabe')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Betrag', max_digits=10)),
                ('category', models.CharField(choices=[('travel', 'Reisekosten'), ('meals', 'Verpflegung'), ('transport', 'Transport'), ('accommodation', 'Unterkunft'), ('communication', 'Kommunikation'), ('office_supplies', 'Büromaterial'), ('training', 'Fortbildung'), ('client_entertainment', 'Kundenbetreuung'), ('other', 'Sonstiges')], help_text='Kategorie', max_length=30)),
                ('description', models.TextField(help_text='Beschreibung')),
                ('receipt_url', models.URLField(blank=True, help_text='Beleg-URL', null=True)),
                ('status', models.CharField(choices=[('submitted', 'Eingereicht'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('paid', 'Bezahlt')], default='submitted', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Ablehnungsgrund', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.tenant')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='expenses_tenant__dfc47d_idx'), models.Index(fields=['employee', 'date'], name='expenses_employe_8cee19_idx'), models.Index(fields=['status'], name='expenses_status_86293f_idx'), models.Index(fields=['category'], name='expenses_categor_a6f264_idx')],
            },
        ),
        migrations.CreateModel(
            name='HRDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Titel', max_length=200)),
                ('document_type', models.CharField(choices=[('contract', 'Arbeitsvertrag'), ('certificate', 'Zeugnis'), ('id_card', 'Personalausweis'), ('passport', 'Reisepass'), ('driver_license', 'Führerschein'), ('qualification', 'Qualifikation'), ('training_certificate', 'Fortbildungsnachweis'), ('medical_certificate', 'Arbeitsunfähigkeitsbescheinigung'), ('other', 'Sonstiges')], help_text='Dokumenttyp', max_length=30)),
                ('file_url', models.URLField(help_text='Datei-URL')),
                ('file_size', models.IntegerField(blank=True, help_text='Dateigröße in Bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME-Typ', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Beschreibung', null=True)),
                ('expires_at', models.DateField(blank=True, help_text='Ablaufdatum', null=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Vertraulich')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to='app.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to='app.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_hr_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='hr_document_tenant__79fa01_idx'), models.Index(fields=['employee', 'document_type'], name='hr_document_employe_a57ed9_idx'), models.Index(fields=['expires_at'], name='hr_document_expires_55c07d_idx'), models.Index(fields=['is_confidential'], name='hr_document_is_conf_d242e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Urlaubsbeginn')),
                ('end_date', models.DateField(help_text='Urlaubsende')),
                ('leave_type', models.CharField(choices=[('vacation', 'Urlaub'), ('sick', 'Krankheit'), ('personal', 'Persönlich'), ('maternity', 'Mutterschutz'), ('paternity', 'Vaterschaftsurlaub'), ('study', 'Bildungsurlaub'), ('other', 'Sonstiges')], default='vacation', max_length=20)),
                ('days_count', models.DecimalField(decimal_places=1, help_text='Anzahl Urlaubstage', max_digits=4)),
                ('reason', models.TextField(blank=True, help_text='Begründung', null=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Ablehnungsgrund', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='app.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='app.tenant')),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='leave_reque_tenant__b74d62_idx'), models.Index(fields=['tenant', 'status'], name='leave_reque_tenant__e374b2_idx'), models.Index(fields=['employee', 'start_date'], name='leave_reque_employe_f6da1d_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_reque_start_d_08703b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Datum')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Überstunden', max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Überstundenzuschlag', max_digits=5)),
                ('reason', models.TextField(help_text='Begründung')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Ablehnungsgrund', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='app.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='app.tenant')),
            ],
            options={
                'db_table': 'overtime',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='overtime_tenant__1e8bc2_idx'), models.Index(fields=['employee', 'date'], name='overtime_employe_2645a4_idx'), models.Index(fields=['approved'], name='overtime_approve_51c8cc_idx')],
            },
        ),
    ]
