# Generated by Django 5.2.7 on 2025-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_add_hr_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_days',
            field=models.IntegerField(default=30, help_text='Jährliche Urlaubstage'),
        ),
        migrations.AddField(
            model_name='employee',
            name='expense_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Spesen-Limit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Überstunden-Saldo', max_digits=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='remaining_leave_days',
            field=models.IntegerField(default=30, help_text='Verbleibende Urlaubstage'),
        ),
    ]
