# Generated by Django 5.2.7 on 2025-10-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_employee_annual_leave_days_employee_expense_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], help_text='Energieeffizienzklasse', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertyfeatures',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], help_text='Energieeffizienzklasse', max_length=10, null=True),
        ),
    ]
