# Generated by Django 5.2.7 on 2025-10-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_property_energy_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Sonstige Angaben und Informationen', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='equipment_description',
            field=models.TextField(blank=True, help_text='Detaillierte Ausstattungsbeschreibung', null=True),
        ),
    ]
