# Generated by Django 5.2.7 on 2025-10-24 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_add_equipment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Eigentümer'), ('agent', 'Makler'), ('manager', 'Verwalter'), ('tenant', 'Mieter'), ('buyer', 'Käufer'), ('interested', 'Interessent'), ('contact_person', 'Ansprechpartner')], help_text='Rolle des Kontakts', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Hauptkontakt für diese Rolle')),
                ('notes', models.TextField(blank=True, help_text='Notizen zur Verknüpfung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_contacts',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='availability_date',
            field=models.DateField(blank=True, help_text='Verfügbar ab', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Provision in %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='condition_status',
            field=models.CharField(blank=True, choices=[('neuwertig', 'Neuwertig'), ('saniert', 'Saniert'), ('renovierungsbedürftig', 'Renovierungsbedürftig'), ('modernisiert', 'Modernisiert'), ('altbau', 'Altbau'), ('unsaniert', 'Unsaniert')], help_text='Zustand der Immobilie', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='construction_phase',
            field=models.CharField(blank=True, help_text="Baujahr-Text (z.B. 'ca. 1990', 'Neubau')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.CharField(blank=True, help_text='Etage (z.B. EG, 1.OG, 2.OG, DG)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='internal_id',
            field=models.CharField(blank=True, help_text='Auftragnummer - eindeutige interne Referenznummer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_modernization',
            field=models.IntegerField(blank=True, help_text='Jahr der letzten Modernisierung', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_description',
            field=models.TextField(blank=True, help_text='Lagebeschreibung', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='object_description',
            field=models.TextField(blank=True, help_text='Objektbeschreibung (zusätzlich zu description)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('carport', 'Carport'), ('tiefgarage', 'Tiefgarage'), ('außenstellplatz', 'Außenstellplatz'), ('keine', 'Keine')], help_text='Art der Stellplätze', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='project_id',
            field=models.CharField(blank=True, help_text='Projekt-ID oder Projektname', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Einheitennummer', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'internal_id'], name='properties_tenant__dee5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['internal_id'], name='properties_interna_97766f_idx'),
        ),
        migrations.AddField(
            model_name='propertycontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_contacts', to='app.contact'),
        ),
        migrations.AddField(
            model_name='propertycontact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertycontact',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_contacts', to='app.property'),
        ),
        migrations.AddIndex(
            model_name='propertycontact',
            index=models.Index(fields=['property', 'role'], name='property_co_propert_aef296_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycontact',
            index=models.Index(fields=['contact', 'role'], name='property_co_contact_4e3671_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycontact',
            index=models.Index(fields=['property', 'is_primary'], name='property_co_propert_696dbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertycontact',
            unique_together={('property', 'contact', 'role')},
        ),
    ]
