# Generated by Django 5.2.7 on 2025-10-24 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_add_property_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal', models.CharField(choices=[('immoscout24', 'Immoscout24'), ('immowelt', 'Immowelt'), ('kleinanzeigen', 'eBay Kleinanzeigen')], help_text='Portal-Name', max_length=50)),
                ('access_token', models.TextField(help_text='OAuth Access Token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth Refresh Token', null=True)),
                ('token_expires_at', models.DateTimeField(help_text='Token-Ablaufzeit')),
                ('scope', models.TextField(help_text='OAuth Scopes (kommagetrennt)')),
                ('portal_user_id', models.CharField(help_text='Benutzer-ID im Portal', max_length=100)),
                ('portal_username', models.CharField(blank=True, help_text='Benutzername im Portal', max_length=200, null=True)),
                ('portal_email', models.EmailField(blank=True, help_text='E-Mail im Portal', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Verbindung ist aktiv')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Letzte Synchronisation', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Letzter Fehler', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_connections', to='app.tenant')),
            ],
            options={
                'db_table': 'portal_connections',
            },
        ),
        migrations.CreateModel(
            name='PortalPublishJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_property_id', models.CharField(blank=True, help_text='Property-ID im Portal', max_length=100, null=True)),
                ('portal_url', models.URLField(blank=True, help_text='URL der Veröffentlichung', null=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('publishing', 'Wird veröffentlicht'), ('published', 'Veröffentlicht'), ('failed', 'Fehlgeschlagen'), ('paused', 'Pausiert'), ('unpublished', 'Zurückgezogen')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Fehlermeldung', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Anzahl Wiederholungsversuche')),
                ('portal_data', models.JSONField(default=dict, help_text='Portal-spezifische Daten')),
                ('sync_data', models.JSONField(default=dict, help_text='Synchronisierte Daten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Veröffentlichungszeit', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Letzte Synchronisation', null=True)),
                ('portal_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_jobs', to='app.portalconnection')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_jobs', to='app.property')),
            ],
            options={
                'db_table': 'portal_publish_jobs',
            },
        ),
        migrations.CreateModel(
            name='PortalSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warnung'), ('error', 'Fehler'), ('success', 'Erfolg')], max_length=20)),
                ('message', models.TextField(help_text='Log-Nachricht')),
                ('details', models.JSONField(default=dict, help_text='Zusätzliche Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portal_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='app.portalconnection')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='app.property')),
            ],
            options={
                'db_table': 'portal_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PropertyContact',
        ),
        migrations.AddIndex(
            model_name='portalconnection',
            index=models.Index(fields=['tenant', 'portal'], name='portal_conn_tenant__785fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='portalconnection',
            index=models.Index(fields=['portal', 'is_active'], name='portal_conn_portal_386d0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portalconnection',
            unique_together={('tenant', 'portal')},
        ),
        migrations.AddIndex(
            model_name='portalpublishjob',
            index=models.Index(fields=['property', 'status'], name='portal_publ_propert_935c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='portalpublishjob',
            index=models.Index(fields=['portal_connection', 'status'], name='portal_publ_portal__a7fd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='portalpublishjob',
            index=models.Index(fields=['status', 'created_at'], name='portal_publ_status_717007_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portalpublishjob',
            unique_together={('property', 'portal_connection')},
        ),
        migrations.AddIndex(
            model_name='portalsynclog',
            index=models.Index(fields=['portal_connection', 'created_at'], name='portal_sync_portal__f40048_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsynclog',
            index=models.Index(fields=['property', 'created_at'], name='portal_sync_propert_6d752e_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsynclog',
            index=models.Index(fields=['level', 'created_at'], name='portal_sync_level_f42fb7_idx'),
        ),
    ]
