# Generated by Django 5.2.7 on 2025-10-24 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_add_portal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Eigentümer'), ('agent', 'Makler'), ('manager', 'Verwalter'), ('tenant', 'Mieter'), ('buyer', 'Käufer'), ('interested', 'Interessent'), ('contact_person', 'Ansprechpartner')], help_text='Rolle des Kontakts', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Hauptkontakt für diese Rolle')),
                ('notes', models.TextField(blank=True, help_text='Notizen zur Verknüpfung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_contacts', to='app.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_contacts', to='app.property')),
            ],
            options={
                'db_table': 'property_contacts',
                'indexes': [models.Index(fields=['property', 'role'], name='property_co_propert_aef296_idx'), models.Index(fields=['contact', 'role'], name='property_co_contact_4e3671_idx'), models.Index(fields=['property', 'is_primary'], name='property_co_propert_696dbe_idx')],
                'unique_together': {('property', 'contact', 'role')},
            },
        ),
    ]
